apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nextcloud
type: Opaque
data:
  password: cG9zdGdyZXNwYXNzd29yZA==

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
data:
  admin-password: YWRtaW5wYXNzd29yZA== 
