apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Sofia"
        - name: FTLCONF_dns_listeningMode
          value: "all"
        - name: FTLCONF_dns_upstreams
          value: "1.1.1.1;8.8.8.8"
        - name: FTLCONF_webserver_api_password
          value: "admin"
        - name: FTLCONF_dns_bogusPriv
          value: "true"
        - name: FTLCONF_dns_dnssec
          value: "true"
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-volume
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - CHOWN
            - NET_BIND_SERVICE
      volumes:
      - name: pihole-volume
        persistentVolumeClaim:
          claimName: pihole-pvc