apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Sofia"
        - name: DNSMASQ_LISTENING
          value: "all"
        - name: PIHOLE_DNS_1
          value: "1.1.1.1"
        - name: PIHOLE_DNS_2
          value: "8.8.8.8"
        - name: WEBPASSWORD
          value: "admin"
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-volume
      volumes:
      - name: pihole-volume
        persistentVolumeClaim:
          claimName: pihole-pvc
