apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels: { app: nextcloud }
  template:
    metadata:
      labels: { app: nextcloud }
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh","-c","until nc -zv postgres 5432; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: nextcloud
          image: nextcloud:27-apache
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: admin-password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.home
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_USER
              value: nextcloud
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password 
            - name: PHP_MEMORY_LIMIT
              value: 512M
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true

          # Give the container time to finish first-time install
          startupProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
                - name: Host
                  value: nextcloud.home
            failureThreshold: 60
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
                - name: Host
                  value: nextcloud.home
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
                - name: Host
                  value: nextcloud.home
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6

      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-nextcloud-secrets
            nodePublishSecretRef:
              name: secrets-store-creds
