apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm
    version: 7.0.0  
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: values.yaml