apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-azure-provider
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
    chart: csi-secrets-store-provider-azure
    targetRevision: v1.7.1
    helm:
      values: |
        secrets-store-csi-driver:
          install: false
        linux:
          enabled: true
        windows:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
