apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-hostnet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          kind: DaemonSet
          service:
            type: ClusterIP
          containerPort:
            http: 80
            https: 443
          config:
            use-forwarded-headers: "true"
        defaultBackend:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
