apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      serviceAccountName: default
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/Sofia"
            - name: FTLCONF_webserver_enabled
              value: "true"
            - name: FTLCONF_webserver_port
              value: "8081"
            - name: FTLCONF_webserver_tls
              value: "false"
            - name: FTLCONF_dns_listeningMode
              value: "all"
            - name: FTLCONF_dns_hosts
              value: |
                192.168.100.100 pihole.home
            - name: FTLCONF_dns_upstreams
              value: "1.1.1.1;8.8.8.8"
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: pi-hole-webserver-secret
                  key: password
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
            - name: pihole-pvc
              mountPath: /etc/pihole/
            - name: pihole-pvc
              mountPath: /etc/dnsmasq.d/
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-pihole-secrets
            nodePublishSecretRef:
              name: secrets-store-creds
        - name: pihole-pvc
          persistentVolumeClaim:
            claimName: pihole-pvc
