apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-pihole-secrets
  namespace: pihole
spec:
  provider: azure
  secretObjects:
    - secretName: pihole-webserver-secret
      type: Opaque
      data:
        - key: password
          objectName: pi-hole-webserver-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    tenantId: "$(secrets-store-creds:tenantid)"
    clientId: "$(secrets-store-creds:clientid)"
    clientSecret: "$(secrets-store-creds:clientsecret)"
    keyvaultName: "homelabkv01"
    objects: |
      array:
        - |
          objectName: pi-hole-webserver-secret
          objectType: secret
