apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-pihole-secrets
  namespace: pihole
spec:
  provider: azure
  secretObjects:
    - secretName: pi-hole-webserver-secret
      type: Opaque
      data:
        - key: password
          objectName: pi-hole-webserver-secret  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    tenantId: "e6796a05-156c-48d1-a1e8-b6a21d6c90be"
    clientId: "edcfeeee-ebb1-49d1-b73c-0f102a92a88a"
    keyvaultName: "homelabkv01"
    objects: |
      array:
        - |
          objectName: pi-hole-webserver-secret
          objectType: secret
